server:
  port: 8080

spring:
  application:
    name: EmployeeManagementSystem
  datasource:
    url: jdbc:mysql://mysqlcreate.mysql.database.azure.com:3306/employee
    username: azureuser
    password: Kvenky@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



