server:
  port: 8080
spring:
  application:
    name: EmployeeManagementSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Kvenky@12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



